### ISSUE TITLE
version_info is not hash or array errors

### ISSUE THREAD

**Issue by c4t3l** [cyberious/puppet-windows_java#5]
When running a virgin install of the module I receive the following error:

Jan 14 09:17:03 srvgdypuptst01 puppet-master[18395]: version_info is not a hash or array when accessing it with build_number at /etc/puppet/environments/production/modules/windows_java/manifests/jdk.pp:80 on node nyserver.example.com
Jan 14 09:17:03 srvgdypuptst01 puppet-master[18395]: version_info is not a hash or array when accessing it with build_number at /etc/puppet/environments/production/modules/windows_java/manifests/jdk.pp:80 on node myserver.example.com
Jan 14 09:17:03 srvgdypuptst01 puppet-master[18395]: version_info is not a hash or array when accessing it with build_number at /etc/puppet/environments/production/modules/windows_java/manifests/jdk.pp:80 on node myserver.example.com

**manifest config:**

windows_java::jdk{'Install 7u51':
    version => '7u51',
}

**Windows facter output:**

architecture => x64
dir => C:\Program Files\Puppet Labs\Puppet\facter
domain => example.com
env_windows_installdir => C:\Program Files\Puppet Labs\Puppet
facterversion => 2.3.0
fqdn => myserver.example.com
hardwaremodel => x64
hostname => myserver
id => joe_user
interfaces => Local_Area_Connection
ipaddress => XXX.XXX.XXX.XXX
ipaddress_local_area_connection => XXX.XXX.XXX.XXX
is_pe => false
is_virtual => true
kernel => windows
kernelmajversion => 6.1
kernelrelease => 6.1.7601
kernelversion => 6.1.7601
macaddress => XX:XX:XX:XX:XX:XX
macaddress_local_area_connection => XX:XX:XX:XX:XX:XX
manufacturer => Phoenix Technologies LTD
memoryfree => 728.30 MB
memoryfree_mb => 728.30
memorysize => 4.00 GB
memorysize_mb => 4095.55
mtu_local_area_connection => 0
netmask => 255.255.0.0
netmask_local_area_connection => XXX.XXX.0.0
network_local_area_connection => XXX.XXX.0.0
operatingsystem => windows
operatingsystemmajrelease => 2008 R2
operatingsystemrelease => 2008 R2
os => {"name"=>"windows", "family"=>"windows", "release"=>{"major"=>"2008 R2", "
full"=>"2008 R2"}}
osfamily => windows
path => C:\Program Files\Puppet Labs\Puppet\puppet\bin;C:\Program Files\Puppet L
abs\Puppet\facter\bin;C:\Program Files\Puppet Labs\Puppet\hiera\bin;C:\Program F
iles\Puppet Labs\Puppet\bin;C:\Program Files\Puppet Labs\Puppet\sys\ruby\bin;C:\
Program Files\Puppet Labs\Puppet\sys\tools\bin;C:\Windows\system32;C:\Windows;C:
\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;g:\Program Fi
les (x86)\Microsoft SQL Server\110\Tools\Binn\;g:\Program Files\Microsoft SQL Se
rver\110\Tools\Binn\;g:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Prog
ram Files\Puppet Labs\Puppet\bin;g:\Program Files (x86)\Microsoft SQL Server\110
\Tools\Binn\ManagementStudio\;g:\Program Files (x86)\Microsoft SQL Server\110\DT
S\Binn\
physicalprocessorcount => 2
processor0 => Intel(R) Xeon(R) CPU E5540 @ 2.53GHz
processor1 => Intel(R) Xeon(R) CPU E5540 @ 2.53GHz
processorcount => 2
processors => {"models"=>["Intel(R) Xeon(R) CPU E5540 @ 2.53GHz", "Intel(R) Xeon
(R) CPU E5540 @ 2.53GHz"], "count"=>2, "physicalcount"=>2}
productname => VMware Virtual Platform
ps => tasklist.exe
puppet_vardir => C:/ProgramData/PuppetLabs/puppet/var
puppetversion => 3.7.3
rubyplatform => x64-mingw32
rubysitedir => C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/site_ruby/2
.0.0
rubyversion => 2.0.0
serialnumber => blah-blah-blah
system32 => C:\Windows\system32
system_uptime => {"seconds"=>1512940, "hours"=>420, "days"=>17, "uptime"=>"17 da
ys"}
timezone => Central Standard Time
uptime => 17 days
uptime_days => 17
uptime_hours => 420
uptime_seconds => 1512940
virtual => vmware

Am I missing something?

**Comment by yotaka** [comment]
I have exactly the same issue. I tried installing 8u45.

**Comment by cyberious** [comment]
Sorry for the long delay.
Please make sure your hiera data is updated. If you are not using future parse and module data it would not work without either copying the hiera in from the https://github.com/cyberious/puppet-windows_java/blob/master/data/common.yaml or creating one yourself based on the template at the bottom of the readme.  Could you provide the hiera that either of you are using, just the relevant parts.
@yotaka @c4t3l

**Comment by cyberious** [comment]
Closing for above mentioned
